import React from "react";
import Navbar from "../navbar/Navbar";

function App() {

  return (
    <>
      <Navbar />
      <div>
        <h1>Япона мама</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus rerum, iusto magnam dolor neque officiis ea id soluta repudiandae non quidem corrupti illum voluptas quibusdam est vel eveniet perferendis? Quos architecto odio quod, optio voluptatem rerum nam, modi dolorum dignissimos porro illum dolores eos praesentium voluptatibus. Atque aliquid illum perferendis beatae reprehenderit in a quo odio dignissimos. Quia, maiores, iste deleniti quo mollitia nostrum illum excepturi voluptas ipsam id pariatur! Minima, sequi perspiciatis non inventore iure quasi accusantium veniam? Ipsum non, minima amet natus labore voluptatibus, repellat, fuga pariatur quisquam exercitationem tenetur? Illo, sit iste. Est asperiores nisi nulla quas.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus rerum, iusto magnam dolor neque officiis ea id soluta repudiandae non quidem corrupti illum voluptas quibusdam est vel eveniet perferendis? Quos architecto odio quod, optio voluptatem rerum nam, modi dolorum dignissimos porro illum dolores eos praesentium voluptatibus. Atque aliquid illum perferendis beatae reprehenderit in a quo odio dignissimos. Quia, maiores, iste deleniti quo mollitia nostrum illum excepturi voluptas ipsam id pariatur! Minima, sequi perspiciatis non inventore iure quasi accusantium veniam? Ipsum non, minima amet natus labore voluptatibus, repellat, fuga pariatur quisquam exercitationem tenetur? Illo, sit iste. Est asperiores nisi nulla quas.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus rerum, iusto magnam dolor neque officiis ea id soluta repudiandae non quidem corrupti illum voluptas quibusdam est vel eveniet perferendis? Quos architecto odio quod, optio voluptatem rerum nam, modi dolorum dignissimos porro illum dolores eos praesentium voluptatibus. Atque aliquid illum perferendis beatae reprehenderit in a quo odio dignissimos. Quia, maiores, iste deleniti quo mollitia nostrum illum excepturi voluptas ipsam id pariatur! Minima, sequi perspiciatis non inventore iure quasi accusantium veniam? Ipsum non, minima amet natus labore voluptatibus, repellat, fuga pariatur quisquam exercitationem tenetur? Illo, sit iste. Est asperiores nisi nulla quas.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus rerum, iusto magnam dolor neque officiis ea id soluta repudiandae non quidem corrupti illum voluptas quibusdam est vel eveniet perferendis? Quos architecto odio quod, optio voluptatem rerum nam, modi dolorum dignissimos porro illum dolores eos praesentium voluptatibus. Atque aliquid illum perferendis beatae reprehenderit in a quo odio dignissimos. Quia, maiores, iste deleniti quo mollitia nostrum illum excepturi voluptas ipsam id pariatur! Minima, sequi perspiciatis non inventore iure quasi accusantium veniam? Ipsum non, minima amet natus labore voluptatibus, repellat, fuga pariatur quisquam exercitationem tenetur? Illo, sit iste. Est asperiores nisi nulla quas.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus rerum, iusto magnam dolor neque officiis ea id soluta repudiandae non quidem corrupti illum voluptas quibusdam est vel eveniet perferendis? Quos architecto odio quod, optio voluptatem rerum nam, modi dolorum dignissimos porro illum dolores eos praesentium voluptatibus. Atque aliquid illum perferendis beatae reprehenderit in a quo odio dignissimos. Quia, maiores, iste deleniti quo mollitia nostrum illum excepturi voluptas ipsam id pariatur! Minima, sequi perspiciatis non inventore iure quasi accusantium veniam? Ipsum non, minima amet natus labore voluptatibus, repellat, fuga pariatur quisquam exercitationem tenetur? Illo, sit iste. Est asperiores nisi nulla quas.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus rerum, iusto magnam dolor neque officiis ea id soluta repudiandae non quidem corrupti illum voluptas quibusdam est vel eveniet perferendis? Quos architecto odio quod, optio voluptatem rerum nam, modi dolorum dignissimos porro illum dolores eos praesentium voluptatibus. Atque aliquid illum perferendis beatae reprehenderit in a quo odio dignissimos. Quia, maiores, iste deleniti quo mollitia nostrum illum excepturi voluptas ipsam id pariatur! Minima, sequi perspiciatis non inventore iure quasi accusantium veniam? Ipsum non, minima amet natus labore voluptatibus, repellat, fuga pariatur quisquam exercitationem tenetur? Illo, sit iste. Est asperiores nisi nulla quas.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus rerum, iusto magnam dolor neque officiis ea id soluta repudiandae non quidem corrupti illum voluptas quibusdam est vel eveniet perferendis? Quos architecto odio quod, optio voluptatem rerum nam, modi dolorum dignissimos porro illum dolores eos praesentium voluptatibus. Atque aliquid illum perferendis beatae reprehenderit in a quo odio dignissimos. Quia, maiores, iste deleniti quo mollitia nostrum illum excepturi voluptas ipsam id pariatur! Minima, sequi perspiciatis non inventore iure quasi accusantium veniam? Ipsum non, minima amet natus labore voluptatibus, repellat, fuga pariatur quisquam exercitationem tenetur? Illo, sit iste. Est asperiores nisi nulla quas.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus rerum, iusto magnam dolor neque officiis ea id soluta repudiandae non quidem corrupti illum voluptas quibusdam est vel eveniet perferendis? Quos architecto odio quod, optio voluptatem rerum nam, modi dolorum dignissimos porro illum dolores eos praesentium voluptatibus. Atque aliquid illum perferendis beatae reprehenderit in a quo odio dignissimos. Quia, maiores, iste deleniti quo mollitia nostrum illum excepturi voluptas ipsam id pariatur! Minima, sequi perspiciatis non inventore iure quasi accusantium veniam? Ipsum non, minima amet natus labore voluptatibus, repellat, fuga pariatur quisquam exercitationem tenetur? Illo, sit iste. Est asperiores nisi nulla quas.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus rerum, iusto magnam dolor neque officiis ea id soluta repudiandae non quidem corrupti illum voluptas quibusdam est vel eveniet perferendis? Quos architecto odio quod, optio voluptatem rerum nam, modi dolorum dignissimos porro illum dolores eos praesentium voluptatibus. Atque aliquid illum perferendis beatae reprehenderit in a quo odio dignissimos. Quia, maiores, iste deleniti quo mollitia nostrum illum excepturi voluptas ipsam id pariatur! Minima, sequi perspiciatis non inventore iure quasi accusantium veniam? Ipsum non, minima amet natus labore voluptatibus, repellat, fuga pariatur quisquam exercitationem tenetur? Illo, sit iste. Est asperiores nisi nulla quas.</p>
      </div>
    </>
  );
}

export default App;
